import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';

const $=id=>document.getElementById(id);
const mobile=matchMedia('(pointer:coarse)').matches;
let renderer;
try {renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'});} catch(e){$('loading').classList.add('hidden');$('error').classList.remove('hidden');throw e;}
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.3:1.7));
renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene();scene.background=new THREE.Color('#b99b9e');scene.fog=new THREE.FogExp2('#c1998f',.00148);
const camera=new THREE.PerspectiveCamera(53,innerWidth/innerHeight,.1,2600);
const pmrem=new THREE.PMREMGenerator(renderer);const env=pmrem.fromScene(new RoomEnvironment(),.04);scene.environment=env.texture;scene.environmentIntensity=.6;
const hemi=new THREE.HemisphereLight('#adceda','#776044',2);scene.add(hemi);
const sun=new THREE.DirectionalLight('#ffbf81',3.6);sun.position.set(-260,190,-430);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-65;sun.shadow.camera.right=65;sun.shadow.camera.top=65;sun.shadow.camera.bottom=-65;sun.shadow.camera.near=1;sun.shadow.camera.far=700;sun.shadow.bias=-.00035;sun.shadow.normalBias=.08;scene.add(sun,sun.target);
const skyMat=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color('#4a798d')},horizon:{value:new THREE.Color('#fac398')},bottom:{value:new THREE.Color('#b2a7a4')}},vertexShader:'varying vec3 vPos; void main(){vPos=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform vec3 top;uniform vec3 horizon;uniform vec3 bottom;varying vec3 vPos;void main(){float h=normalize(vPos).y;vec3 c=mix(horizon,top,smoothstep(0.0,.85,h));c=mix(c,bottom,smoothstep(0.0,-.3,h));gl_FragColor=vec4(c,1.0);}'});
const sky=new THREE.Mesh(new THREE.SphereGeometry(1900,32,24),skyMat);scene.add(sky);
const sunDisc=new THREE.Mesh(new THREE.SphereGeometry(48,32,20),new THREE.MeshBasicMaterial({color:new THREE.Color(4.4,2.4,1.1),fog:false}));sunDisc.position.set(-660,160,-1390);scene.add(sunDisc);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.28,.55,1.05);composer.addPass(bloom);composer.addPass(new OutputPass());
let seed=8294;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}const range=(a,b)=>a+rand()*(b-a);
const standard=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.8,...extra});
const boxGeo=new THREE.BoxGeometry(1,1,1),planeGeo=new THREE.PlaneGeometry(1,1);
const batches=new Map(),dummy=new THREE.Object3D();
function instance(mat,x,y,z,sx,sy,sz,ry=0){let arr=batches.get(mat);if(!arr){arr=[];batches.set(mat,arr);}dummy.position.set(x,y,z);dummy.rotation.set(0,ry,0);dummy.scale.set(sx,sy,sz);dummy.updateMatrix();arr.push(dummy.matrix.clone());}
function flush(){for(const [mat,arr]of batches){const m=new THREE.InstancedMesh(boxGeo,mat,arr.length);arr.forEach((v,i)=>m.setMatrixAt(i,v));m.receiveShadow=true;m.castShadow=mat!==roadLineMat&&mat!==crossingMat;scene.add(m);}batches.clear();}
function mesh(geo,mat,x=0,y=0,z=0,parent=scene){const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);parent.add(m);return m;}
function plane(mat,x,y,z,w,h,rotation=-Math.PI/2){const m=mesh(planeGeo,mat,x,y,z);m.rotation.x=rotation;m.scale.set(w,h,1);m.receiveShadow=true;return m;}
function textureCanvas(w,h,draw){const c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'),w,h);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();return t;}
const asphaltTex=textureCanvas(256,256,(c,w,h)=>{c.fillStyle='#777c7a';c.fillRect(0,0,w,h);for(let i=0;i<23000;i++){const v=Math.floor(range(60,160));c.fillStyle=`rgba(${v},${v},${v},.18)`;c.fillRect(rand()*w,rand()*h,1,1);}});asphaltTex.wrapS=asphaltTex.wrapT=THREE.RepeatWrapping;asphaltTex.repeat.set(100,130);
const ground=plane(standard('#273138',{map:asphaltTex,roughness:.72,metalness:.15}),0,-.045,0,880,1220);
const sandMat=standard('#b4a17e');plane(sandMat,-403,-.2,0,78,1400);const grass=standard('#56615a');plane(grass,-352,.01,0,42,1200);
const oceanMat=new THREE.ShaderMaterial({uniforms:{time:{value:0},sunColor:{value:new THREE.Color('#f4b577')}},vertexShader:`varying vec3 vWorld; varying vec3 vNormal;uniform float time;void main(){vec3 p=position;p.z+=sin(p.x*.022+time*.6)*.35+sin(p.y*.028-time*.4)*.3;vec4 wp=modelMatrix*vec4(p,1.);vWorld=wp.xyz;gl_Position=projectionMatrix*viewMatrix*wp;}`,fragmentShader:`varying vec3 vWorld;uniform float time;void main(){float w=sin(vWorld.x*.07+vWorld.z*.032+time)*sin(vWorld.z*.24-time*.8);float fine=sin(vWorld.z*1.2+sin(vWorld.x*.4)+time*.8);float gleam=pow(max(0.,w),15.);float band=exp(-pow((vWorld.z+900.)/900.,2.));vec3 col=mix(vec3(.11,.26,.30),vec3(.50,.59,.57),w*.18+.35);col+=vec3(.63,.36,.18)*gleam*.8*band;col+=fine*.013;gl_FragColor=vec4(col,1.);}`});
const ocean=mesh(new THREE.PlaneGeometry(1900,3200,140,150),oceanMat,-1368,-.68,0);ocean.rotation.x=-Math.PI/2;
const white=standard('#d4c9ac'),curbMat=standard('#aea99b'),sidewalk=standard('#999990',{roughness:.92}),roadLineMat=standard('#b7a078'),crossingMat=standard('#c2bcb1'),darkMat=standard('#29333a'),poleMat=standard('#414b4c',{metalness:.4}),lampMat=standard('#fff6d3',{emissive:'#ffd392',emissiveIntensity:2.7}),glassMat=standard('#3b525b',{roughness:.14,metalness:.75}),roofMat=standard('#797d78');
const roadsX=[-320,-160,0,160,320],roadsZ=[-480,-320,-160,0,160,320,480];
for(const x of roadsX){for(let z=-560;z<560;z+=12){if(roadsZ.some(v=>Math.abs(z-v)<20))continue;instance(roadLineMat,x,.015,z,.2,.025,6);instance(roadLineMat,x-1,.015,z,.16,.025,6);}for(const dx of [-14.5,14.5]){instance(curbMat,x+dx,.14,0,.35,.28,1150);instance(sidewalk,x+dx+Math.sign(dx)*2.3,.10,0,4.3,.2,1150);}}
for(const z of roadsZ){for(let x=-338;x<350;x+=12){if(roadsX.some(v=>Math.abs(x-v)<19))continue;instance(roadLineMat,x,.02,z,6,.025,.2);instance(roadLineMat,x,.02,z+1,6,.025,.16);}for(const dz of [-14.5,14.5])instance(sidewalk,0,.105,z+dz+Math.sign(dz)*2.3,685,.21,4.5);for(const x of roadsX){for(const side of [-1,1])for(let k=-4;k<=4;k++){instance(crossingMat,x+k*2.15,.024,z+side*19,1.05,.03,5.2);instance(crossingMat,x+side*19,.024,z+k*2.15,5.2,.03,1.05);}}}
// The boulevard has a continuous ocean promenade.
instance(sidewalk,-373,.15,0,5,.3,1210);instance(white,-379,.5,0,.4,1,1210);
const colliders=[];
const buildingMaterials=[];
for(let k=0;k<6;k++){
 const tex=textureCanvas(256,512,(c,w,h)=>{c.fillStyle=['#7f9293','#9a998e','#6f858c','#a3a598','#637b82','#aaa092'][k];c.fillRect(0,0,w,h);for(let yy=6;yy<h;yy+=18)for(let xx=5;xx<w;xx+=16){const lit=rand()>.69;c.fillStyle=lit?['#efcda0','#c8b98d','#dfc8a1'][Math.floor(rand()*3)]:['#324955','#455b63','#617179'][Math.floor(rand()*3)];c.fillRect(xx,yy,11,13);c.fillStyle='#c2c7b130';c.fillRect(xx,yy,11,2);}for(let xx=0;xx<w;xx+=64){c.fillStyle='#d7d8c14a';c.fillRect(xx,0,3,h);}});
 buildingMaterials.push(standard('#eeeeea',{map:tex,roughness:k%2?.66:.35,metalness:k%2?.1:.35}));
}
const brickMat=standard('#928577');const shopMats=[standard('#484f53'),standard('#916e58'),standard('#b1a083')];
for(let ix=0;ix<4;ix++)for(let iz=0;iz<6;iz++){
 const centerX=(roadsX[ix]+roadsX[ix+1])/2,centerZ=(roadsZ[iz]+roadsZ[iz+1])/2;
 instance(sidewalk,centerX,.13,centerZ,125,.26,125);
 for(let i=0;i<2;i++)for(let j=0;j<2;j++){
 const x=centerX+(i-.5)*61+range(-3,3),z=centerZ+(j-.5)*61+range(-3,3),downtown=Math.max(0,1-Math.hypot(x-130,z+180)/450);
 const w=range(34,48),d=range(34,48),h=range(10,32)+downtown*range(15,112),mat=buildingMaterials[Math.floor(rand()*6)];
 instance(mat,x,h/2+.25,z,w,h,d);instance(roofMat,x,h+.55,z,w+1,.6,d+1);
 instance(darkMat,x,1.9,z,w+.8,3.3,d+.8);instance(glassMat,x,2.1,z,w+1,2.3,d+1);
 instance(white,x,4.05,z,w+1.3,.5,d+1.3);
 instance(roofMat,x+range(-w/4,w/4),h+2,z+range(-d/4,d/4),w*.32,3,d*.3);
 if(h>50){instance(white,x,h*.66,z,w+.7,.45,d+.7);instance(white,x,h*.33,z,w+.7,.45,d+.7);instance(poleMat,x,h+7,z,.3,12,.3);}
 colliders.push({x,z,w:w/2+1,d:d/2+1});
 }
}
// Distant skyline and hills make the drivable city feel connected to a larger coast.
for(let i=0;i<40;i++){const x=range(-260,750),z=range(-1020,-690),h=range(35,180);instance(buildingMaterials[i%6],x,h/2,z,range(24,55),h,range(25,58));}
const mountainMat=standard('#737c80');for(let i=0;i<18;i++){const m=mesh(new THREE.ConeGeometry(range(120,260),range(90,230),5),mountainMat,range(400,1200),45,range(-1250,700));m.rotation.y=rand()*6;}
// Palm leaves share one merged geometry, with gentle downward-curving leaflets.
const trunkMat=standard('#77674f'),leafMat=standard('#405653',{side:THREE.DoubleSide,roughness:.85});
const palmLeafParts=[];
for(let j=0;j<9;j++){const angle=j/9*Math.PI*2;for(let k=0;k<5;k++){const a=k/5,b=(k+1)/5;const r1=a*6.5,r2=b*6.5,y1=Math.sin(a*Math.PI)*1.9-a*1.7,y2=Math.sin(b*Math.PI)*1.9-b*1.7,width=Math.sin((a+.1)*Math.PI)*.85;const dx=Math.cos(angle),dz=Math.sin(angle),px=-dz,pz=dx;const verts=[dx*r1+px*width,y1,dz*r1+pz*width,dx*r1-px*width,y1,dz*r1-pz*width,dx*r2,y2,dz*r2];const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.computeVertexNormals();palmLeafParts.push(g);}}
const palmLeaves=mergeGeometries(palmLeafParts),palmTrunk=new THREE.CylinderGeometry(.20,.41,1,7);
const palms=[];for(let z=-550;z<=550;z+=34){palms.push([-352,z]);if(!roadsZ.some(v=>Math.abs(z-v)<23))palms.push([-301,z]);}for(let x=-145;x<=320;x+=80)for(let z of [-499,499])palms.push([x,z]);
const leafInstances=new THREE.InstancedMesh(palmLeaves,leafMat,palms.length),trunkInstances=new THREE.InstancedMesh(palmTrunk,trunkMat,palms.length);
palms.forEach(([x,z],i)=>{const h=range(10,15);dummy.position.set(x,h/2,z);dummy.scale.set(1,h,1);dummy.rotation.set(0,rand()*6,.025);dummy.updateMatrix();trunkInstances.setMatrixAt(i,dummy.matrix);dummy.position.set(x,h,z);dummy.scale.set(1,1,1);dummy.rotation.set(0,rand()*6,0);dummy.updateMatrix();leafInstances.setMatrixAt(i,dummy.matrix);});trunkInstances.castShadow=true;leafInstances.castShadow=true;scene.add(leafInstances,trunkInstances);
for(const x of roadsX)for(let z=-530;z<=530;z+=66){if(roadsZ.some(v=>Math.abs(z-v)<23))continue;for(const side of [-1,1]){const px=x+side*13.1;instance(poleMat,px,4.5,z,.15,9,.15);instance(poleMat,px-side*1.3,8.8,z,2.8,.12,.13);instance(lampMat,px-side*2.4,8.7,z,.8,.15,.42);}}
// Street-level signs use readable canvas lettering on simple physical signboards.
function sign(text,x,y,z,color='#e2a57a',ry=0,width=14){const t=textureCanvas(512,128,c=>{c.fillStyle='#233740';c.fillRect(0,0,512,128);c.strokeStyle=color;c.lineWidth=5;c.strokeRect(6,6,500,116);c.fillStyle=color;c.font='600 42px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText(text,256,65);});const m=mesh(new THREE.PlaneGeometry(width,width/4),standard('#ffffff',{map:t,emissive:'#ffffff',emissiveMap:t,emissiveIntensity:.35}),x,y,z);m.rotation.y=ry;}
sign('PACIFIC MOTEL',-239,8,174,'#f8bd82',Math.PI/2,18);sign('COASTAL',-240,38,-101,'#b9d8ce',0,18);sign('VISTA',81,91,-218,'#f4c88c',0,16);
// Colored shop awnings and a few rooftop signs keep the city from reading as an empty grid.
for(const c of colliders){const mat=shopMats[Math.floor(rand()*3)];instance(mat,c.x,3.7,c.z-c.d-.8,c.w*1.5,.2,2.3);}
flush();
// Cars face local -Z. A low, bevelled silhouette and layered lights define the coupe.
const carBodyMat=standard('#df6339',{metalness:.6,roughness:.25});
const tireMat=standard('#151b1e',{roughness:.88}),rimMat=standard('#9ba3a4',{metalness:.9,roughness:.28}),trimMat=standard('#20272a',{metalness:.5,roughness:.3}),carGlass=standard('#273f49',{metalness:.8,roughness:.13});
const headMat=standard('#fff7dc',{emissive:'#fff0bb',emissiveIntensity:3.3}),tailMat=standard('#ba2416',{emissive:'#ff351b',emissiveIntensity:3.2});
function hull(sections,mat,parent){const vertices=[],indices=[];for(const [z,w,b,t]of sections){vertices.push(-w,b,z,w,b,z,-w,t,z,w,t,z);}for(let i=0;i<sections.length-1;i++){const a=i*4,b=a+4;indices.push(a,a+1,b+1,a,b+1,b,a+2,b+2,b+3,a+2,b+3,a+3,a,b,a+2,b,b+2,a+2,a+1,a+3,b+1,a+3,b+3,b+1);}const l=(sections.length-1)*4;indices.push(0,2,3,0,3,1,l,l+1,l+3,l,l+3,l+2);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.setIndex(indices);g.setAttribute('uv',new THREE.Float32BufferAttribute(new Float32Array(vertices.length/3*2),2));g.computeVertexNormals();const m=mesh(g,mat,0,0,0,parent);m.castShadow=true;return m;}
function part(parent,geo,mat,x,y,z,sx=1,sy=1,sz=1){const m=mesh(geo,mat,x,y,z,parent);m.scale.set(sx,sy,sz);m.castShadow=true;return m;}
const tireGeo=new THREE.CylinderGeometry(.48,.48,.30,20);tireGeo.rotateZ(Math.PI/2);const rimGeo=new THREE.CylinderGeometry(.30,.30,.315,12);rimGeo.rotateZ(Math.PI/2);
function createCar(bodyMat,traffic=false){const g=new THREE.Group(),shell=new THREE.Group();g.add(shell);const wheels=[];
 hull([[-2.55,.88,.4,.66],[-2.25,1.03,.38,.88],[-1.1,1.06,.4,1.05],[1.5,1.06,.4,1.05],[2.45,.94,.44,.82]],bodyMat,shell);
 hull([[-1.15,.86,.98,1.04],[-.48,.77,1.02,1.72],[.72,.78,1.02,1.76],[1.43,.9,1.02,1.06]],carGlass,shell);
 part(shell,boxGeo,bodyMat,.0,1.77,.12,1.57,.09,1.25);
 part(shell,boxGeo,trimMat,0,.41,-2.52,1.87,.12,.26);part(shell,boxGeo,trimMat,0,.42,2.43,1.85,.13,.23);
 part(shell,boxGeo,trimMat,0,.57,-2.53,.95,.19,.04);
 for(const side of [-1,1]){part(shell,boxGeo,headMat,side*.65,.76,-2.40,.48,.08,.09);part(shell,boxGeo,tailMat,side*.6,.8,2.44,.6,.10,.05);part(shell,boxGeo,trimMat,side*1.06,.46,0,.12,.15,3.65);part(shell,boxGeo,bodyMat,side*1.12,1.12,-.58,.3,.13,.27);part(shell,boxGeo,trimMat,side*.87,1.26,.77,.08,.78,.08);for(const z of [-1.58,1.52]){const wheel=new THREE.Group();wheel.position.set(side*1.01,.49,z);part(wheel,tireGeo,tireMat,0,0,0);part(wheel,rimGeo,rimMat,side*.016,0,0);g.add(wheel);wheels.push(wheel);}}
 part(shell,boxGeo,trimMat,0,1.06,2.07,1.87,.10,.36);for(const side of [-1,1])part(shell,boxGeo,trimMat,side*.64,.49,2.56,.28,.12,.13);
 const plateTex=textureCanvas(128,32,c=>{c.fillStyle='#d9d8c5';c.fillRect(0,0,128,32);c.fillStyle='#263b47';c.font='bold 20px monospace';c.textAlign='center';c.fillText('PACIFIC',64,24);});part(shell,planeGeo,standard('#ffffff',{map:plateTex}),0,.61,2.457,.48,.12,1);
 if(traffic){const byMat=new Map();shell.updateMatrixWorld(true);for(const child of [...shell.children])if(child.isMesh){const geo=child.geometry.clone();geo.applyMatrix4(child.matrix);if(!byMat.has(child.material))byMat.set(child.material,[]);byMat.get(child.material).push(geo);shell.remove(child);}for(const [mat,gs]of byMat){const m=mesh(mergeGeometries(gs.map(g=>g.index?g.toNonIndexed():g)),mat,0,0,0,shell);m.castShadow=true;}}
 return {group:g,shell,wheels};}
const player=createCar(carBodyMat);scene.add(player.group);
// Car contact shadow remains crisp even on devices using the lighter graphics mode.
const shadowTex=textureCanvas(128,128,(c,w,h)=>{const gr=c.createRadialGradient(w/2,h/2,8,w/2,h/2,64);gr.addColorStop(0,'#000000c0');gr.addColorStop(.6,'#00000080');gr.addColorStop(1,'#00000000');c.fillStyle=gr;c.fillRect(0,0,w,h);});const blob=plane(new THREE.MeshBasicMaterial({map:shadowTex,transparent:true,depthWrite:false}),-326,.028,246,4,7);
const traffic=[];const trafficColors=['#acb4ac','#4b7182','#94714e','#bbc0be','#3c4447','#b16847'];
for(let i=0;i<18;i++){const alongZ=i<12,road=alongZ?roadsX[i%roadsX.length]:roadsZ[i%roadsZ.length],dir=i%2?1:-1,c=createCar(standard(trafficColors[i%6],{roughness:.33,metalness:.45}),true);scene.add(c.group);traffic.push({...c,alongZ,road,dir,position:range(-490,490),speed:range(9,16)});}
// Checkpoint beams remain visible from a distance, with a ground ring marking the exact target.
const gate=new THREE.Group();const gateMat=new THREE.MeshBasicMaterial({color:'#ffd08a',transparent:true,opacity:.76,depthWrite:false});
for(const x of [-10,10])part(gate,new THREE.CylinderGeometry(.12,.2,14,8),gateMat,x,7,0);
const ring=mesh(new THREE.TorusGeometry(9,.17,8,64),gateMat,0,.18,0,gate);ring.rotation.x=-Math.PI/2;
const gateArrow=mesh(new THREE.ConeGeometry(1.3,2.1,3),new THREE.MeshBasicMaterial({color:'#ffb16c'}),0,10,0,gate);gateArrow.rotation.z=Math.PI;
scene.add(gate);gate.visible=false;
const route=[[-326,40],[-326,-310],[-166,-326],[-6,-326],[154,-326],[166,-6],[6,154],[-314,166]];
let state='intro',paused=false,mode='free',speed=0,heading=0,vx=0,vz=0,steer=0,nitro=100,boosting=false,cameraMode=0,raceTime=0,checkpoint=0,quality=mobile?'medium':'high',distanceTravelled=0;
const spawn={x:-326,z:246};player.group.position.set(spawn.x,.08,spawn.z);let lastX=spawn.x,lastZ=spawn.z;
const keys=new Set();const clock=new THREE.Clock();let time=0,frame=0,toastTimer,started=false;
const camDesired=new THREE.Vector3(),camTarget=new THREE.Vector3(),lookTarget=new THREE.Vector3(),up=new THREE.Vector3(0,1,0);
const skidMat=new THREE.MeshBasicMaterial({color:'#101719',transparent:true,opacity:.32,depthWrite:false});const skid=new THREE.InstancedMesh(planeGeo,skidMat,250);skid.instanceMatrix.setUsage(THREE.DynamicDrawUsage);let skidIndex=0;for(let i=0;i<250;i++){dummy.scale.set(0,0,0);dummy.updateMatrix();skid.setMatrixAt(i,dummy.matrix);}scene.add(skid);
const minimap=$('minimap'),ctx=minimap.getContext('2d');let expandedMap=false;
const sound={enabled:false,ctx:null,osc:null,gain:null,filter:null};
function enableSound(){try{if(!sound.ctx){sound.ctx=new (window.AudioContext||window.webkitAudioContext)();sound.osc=sound.ctx.createOscillator();sound.osc.type='sawtooth';sound.filter=sound.ctx.createBiquadFilter();sound.filter.type='lowpass';sound.filter.frequency.value=200;sound.gain=sound.ctx.createGain();sound.gain.gain.value=0;sound.osc.connect(sound.filter).connect(sound.gain).connect(sound.ctx.destination);sound.osc.start();}sound.ctx.resume();}catch{} }
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600);}
function resetCar(){let x=spawn.x,z=spawn.z,h=0;if(state==='play'&&mode==='free'){const p=player.group.position;const rx=roadsX.reduce((a,b)=>Math.abs(a-p.x)<Math.abs(b-p.x)?a:b);x=rx-6;z=THREE.MathUtils.clamp(p.z,-520,520);}player.group.position.set(x,.08,z);speed=0;vx=0;vz=0;heading=h;steer=0;lastX=x;lastZ=z;player.group.rotation.set(0,h,0);if(state==='play'&&mode==='race'){raceTime=0;checkpoint=0;setGate();}snapCamera();}
function begin(newMode){mode=newMode;state='play';paused=false;keys.clear();$('intro').classList.add('hidden');$('intro-location').classList.add('hidden');$('intro-footer').classList.add('hidden');$('hud').classList.remove('hidden');document.body.classList.add('playing');document.body.classList.toggle('racing',mode==='race');$('race').classList.toggle('hidden',mode!=='race');$('start-trial').classList.toggle('hidden',mode==='race');$('mode-label').textContent=mode==='race'?'TIME TRIAL':'FREE ROAM';$('mission-title').textContent=mode==='race'?'Follow the afterglow.':'Take the long way home.';$('mission-subtitle').textContent=mode==='race'?'Pass through all 8 golden checkpoints.':'Explore Vista Pacífica at your own pace.';raceTime=0;checkpoint=0;nitro=100;player.group.position.set(spawn.x,.08,spawn.z);speed=0;vx=0;vz=0;heading=0;steer=0;player.group.rotation.y=0;lastX=spawn.x;lastZ=spawn.z;gate.visible=mode==='race';setGate();snapCamera();enableSound();toast(mode==='race'?'SUNSET RUN · GO':'WELCOME TO VISTA PACÍFICA');}
function setGate(){if(checkpoint>=route.length)return;gate.position.set(route[checkpoint][0],.1,route[checkpoint][1]);$('checkpoint-count').textContent=`${checkpoint+1} / ${route.length}`;}
function finishRace(){paused=true;keys.clear();$('final-time').textContent=formatTime(raceTime);let best=null;try{best=Number(localStorage.getItem('pacific-best'))||null;if(!best||raceTime<best){localStorage.setItem('pacific-best',String(raceTime));$('best-time').textContent='A new personal best. Make the coast remember it.';}else $('best-time').textContent='PERSONAL BEST  '+formatTime(best);}catch{$('best-time').textContent='Eight checkpoints. One perfect coastline.';}$('result').showModal();gate.visible=false;}
function formatTime(t){const min=Math.floor(t/60),sec=Math.floor(t%60),cs=Math.floor(t*100%100);return `${String(min).padStart(2,'0')}:${String(sec).padStart(2,'0')}.${String(cs).padStart(2,'0')}`;}
function pauseGame(settings=false){if($('result').open)return;paused=true;keys.clear();$('menu-title').textContent=settings?'Make it your drive.':'Take a breather.';$('menu-description').textContent=settings?'Settle in. Find your favorite view.':'The coast will be right here.';$('resume').textContent=state==='intro'?'BACK TO THE COAST':'BACK TO THE DRIVE';$('back-title').classList.toggle('hidden',state==='intro');$('restart-race').textContent=mode==='race'&&state==='play'?'RESTART SUNSET RUN':'START SUNSET RUN';if(!$('menu').open)$('menu').showModal();}
function closeMenu(){$('menu').close();paused=false;keys.clear();}
function cameraSwitch(value){cameraMode=value??(cameraMode+1)%3;$('camera-select').value=cameraMode;if(state==='play'){toast(['CHASE CAMERA','WIDE CHASE CAMERA','HOOD CAMERA'][cameraMode]);snapCamera();}}
function getCamera(){const p=player.group.position,sh=Math.sin(heading),ch=Math.cos(heading);const v=Math.min(Math.abs(speed)/50,1);if(cameraMode===2){camDesired.set(p.x-sh*1.3,p.y+1.42,p.z-ch*1.3);camTarget.set(p.x-sh*35,2.1,p.z-ch*35);}else{const d=cameraMode===1?13:8.7;camDesired.set(p.x+sh*(d+v*1.7),p.y+(cameraMode===1?6.3:4.05)+v*.35,p.z+ch*(d+v*1.7));camTarget.set(p.x-sh*9,p.y+1.4,p.z-ch*9);}}
function snapCamera(){getCamera();camera.position.copy(camDesired);lookTarget.copy(camTarget);camera.lookAt(lookTarget);}
function move(dt){const p=player.group.position;lastX=p.x;lastZ=p.z;let throttle=keys.has('KeyW')||keys.has('ArrowUp'),braking=keys.has('KeyS')||keys.has('ArrowDown'),handbrake=keys.has('Space');const targetSteer=(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)-(keys.has('KeyD')||keys.has('ArrowRight')?1:0);steer=THREE.MathUtils.damp(steer,targetSteer,7,dt);
 boosting=(keys.has('ShiftLeft')||keys.has('ShiftRight'))&&throttle&&nitro>1&&speed>3;nitro=THREE.MathUtils.clamp(nitro+(boosting?-24:11)*dt,0,100);
 if(throttle)speed+= (boosting?32:18)*(speed<0?1.8:1)*dt;
 if(braking)speed-= (speed>1?32:11)*dt;
 if(!throttle&&!braking)speed=THREE.MathUtils.damp(speed,0,.27,dt);
 speed-=speed*Math.abs(speed)*.0033*dt;
 if(handbrake)speed=THREE.MathUtils.damp(speed,0,1.05,dt);
 speed=THREE.MathUtils.clamp(speed,-11,boosting?65:47);
 const yaw=steer*speed*.048/(1+Math.abs(speed)*.023)*(handbrake?1.75:1);heading+=yaw*dt;
 const desiredX=-Math.sin(heading)*speed,desiredZ=-Math.cos(heading)*speed;const grip=handbrake?1.9:8.5;vx=THREE.MathUtils.damp(vx,desiredX,grip,dt);vz=THREE.MathUtils.damp(vz,desiredZ,grip,dt);p.x+=vx*dt;p.z+=vz*dt;
 if(p.x< -369||p.x>363||p.z< -568||p.z>568){p.x=THREE.MathUtils.clamp(p.x,-369,363);p.z=THREE.MathUtils.clamp(p.z,-568,568);speed*=-.18;vx*=.2;vz*=.2;}
 for(const c of colliders){if(Math.abs(p.x-c.x)>c.w+2||Math.abs(p.z-c.z)>c.d+2)continue;let cx=THREE.MathUtils.clamp(p.x,c.x-c.w,c.x+c.w),cz=THREE.MathUtils.clamp(p.z,c.z-c.d,c.z+c.d),dx=p.x-cx,dz=p.z-cz,d=Math.hypot(dx,dz);if(d<1.35){if(d<.001){p.x=lastX;p.z=lastZ;}else{p.x+=dx/d*(1.4-d);p.z+=dz/d*(1.4-d);}speed*=-.2;vx*=.1;vz*=.1;}}
 for(const t of traffic){const q=t.group.position,dx=p.x-q.x,dz=p.z-q.z,d=Math.hypot(dx,dz);if(d<2.5){if(d>.01){p.x+=dx/d*(2.55-d);p.z+=dz/d*(2.55-d);}speed*=-.25;vx*=.15;vz*=.15;}}
 player.group.rotation.y=heading;player.shell.rotation.z=THREE.MathUtils.damp(player.shell.rotation.z,steer*Math.min(Math.abs(speed)/45,1)*.045,5,dt);player.shell.rotation.x=THREE.MathUtils.damp(player.shell.rotation.x,throttle?-.012:braking?.025:0,4,dt);
 player.wheels.forEach((w,i)=>{w.rotation.x-=speed*dt/.48;if(i%2===0)w.rotation.y=steer*.35;});blob.position.set(p.x,.03,p.z);blob.rotation.z=-heading;distanceTravelled+=Math.abs(speed)*dt;
 if(handbrake&&Math.abs(speed)>8&&frame%3===0){for(const side of [-1,1]){dummy.position.set(p.x+Math.cos(heading)*side*.87+Math.sin(heading)*1.5,.035,p.z-Math.sin(heading)*side*.87+Math.cos(heading)*1.5);dummy.rotation.set(-Math.PI/2,0,-heading);dummy.scale.set(.28,1.4,1);dummy.updateMatrix();skid.setMatrixAt(skidIndex++%250,dummy.matrix);}skid.instanceMatrix.needsUpdate=true;}
 if(mode==='race'&&checkpoint<route.length){raceTime+=dt;const [gx,gz]=route[checkpoint];const abx=p.x-lastX,abz=p.z-lastZ,len=abx*abx+abz*abz;const t=len?THREE.MathUtils.clamp(((gx-lastX)*abx+(gz-lastZ)*abz)/len,0,1):0;const d=Math.hypot(gx-lastX-abx*t,gz-lastZ-abz*t);if(d<12){checkpoint++;if(checkpoint===route.length){finishRace();}else{setGate();toast(`CHECKPOINT ${checkpoint} / ${route.length}`);$('checkpoint-flash').classList.add('flash');setTimeout(()=>$('checkpoint-flash').classList.remove('flash'),160);}}}
}
function updateTraffic(dt){for(const t of traffic){t.position+=t.speed*t.dir*dt;const limit=t.alongZ?554:352;if(t.position>limit)t.position=-limit;if(t.position< -limit)t.position=limit;const p=t.group.position;if(t.alongZ){p.set(t.road+(t.dir>0?-6:6),.05,t.position);t.group.rotation.y=t.dir>0?Math.PI:0;}else{p.set(t.position,.05,t.road+(t.dir>0?6:-6));t.group.rotation.y=t.dir>0?-Math.PI/2:Math.PI/2;}}}
function drawMap(){const w=minimap.width,h=minimap.height,p=player.group.position;ctx.fillStyle='#162b33';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w/2,h*.55);const scale=expandedMap?.40:.70;ctx.scale(scale,scale);ctx.translate(expandedMap?25:-p.x,expandedMap?0:-p.z);ctx.fillStyle='#315762';ctx.fillRect(-1800,-1800,1415,3600);ctx.fillStyle='#4b615d';ctx.fillRect(-385,-1300,39,2600);ctx.fillStyle='#263b40';for(const c of colliders)ctx.fillRect(c.x-c.w,c.z-c.d,c.w*2,c.d*2);ctx.strokeStyle='#71827f';ctx.lineWidth=12;for(const x of roadsX){ctx.beginPath();ctx.moveTo(x,-560);ctx.lineTo(x,560);ctx.stroke();}for(const z of roadsZ){ctx.beginPath();ctx.moveTo(-339,z);ctx.lineTo(353,z);ctx.stroke();}ctx.strokeStyle='#a5aca0';ctx.lineWidth=1.1;for(const x of roadsX){ctx.beginPath();ctx.moveTo(x,-560);ctx.lineTo(x,560);ctx.stroke();}if(mode==='race'&&checkpoint<route.length){ctx.strokeStyle='#f0b472aa';ctx.lineWidth=3;ctx.setLineDash([6,6]);ctx.beginPath();ctx.moveTo(p.x,p.z);ctx.lineTo(...route[checkpoint]);ctx.stroke();ctx.setLineDash([]);route.forEach(([x,z],i)=>{if(i<checkpoint)return;ctx.beginPath();ctx.arc(x,z,i===checkpoint?10:5,0,Math.PI*2);ctx.fillStyle=i===checkpoint?'#ffc686':'#ffc68666';ctx.fill();});}ctx.translate(p.x,p.z);ctx.rotate(-heading);ctx.shadowColor='#000';ctx.shadowBlur=8;ctx.fillStyle='#f6e6c7';ctx.beginPath();ctx.moveTo(0,-12);ctx.lineTo(8,9);ctx.lineTo(0,5);ctx.lineTo(-8,9);ctx.closePath();ctx.fill();ctx.restore();}
function updateHud(){const kph=Math.round(Math.abs(speed)*3.6);$('speed').textContent=String(kph).padStart(3,'0');$('gear').textContent=speed< -1?'R':kph<2?'N':String(Math.min(6,Math.floor(kph/35)+1));$('tach-fill').style.width=Math.min(100,kph/235*100)+'%';$('boost-fill').style.width=nitro+'%';$('boost-fill').style.background=boosting?'#fff2bf':'#ff794d';const p=player.group.position;$('district').textContent=p.x< -270?'OCEAN DRIVE':p.x>80&&p.z<0?'DOWNTOWN':'PALM DISTRICT';$('road-name').textContent=p.x< -270?'Vista Pacífica':p.z< -250?'Sunset Boulevard':p.z>250?'Southbank':'San Aurelio';const dirs=['N','NW','W','SW','S','SE','E','NE'];$('heading').textContent=dirs[((Math.round(heading/(Math.PI/4))%8)+8)%8];if(mode==='race'){$('race-time').textContent=formatTime(raceTime);if(checkpoint<route.length)$('checkpoint-distance').textContent=Math.round(Math.hypot(route[checkpoint][0]-p.x,route[checkpoint][1]-p.z))+' M';}drawMap();}
function setQuality(q){quality=q;try{localStorage.setItem('pacific-quality',q);}catch{}renderer.setPixelRatio(Math.min(devicePixelRatio,q==='high'?1.7:q==='medium'?1.2:1));bloom.enabled=q!=='low';renderer.shadowMap.enabled=q!=='low';renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);$('quality').value=q;}
$('drive').onclick=()=>begin('free');$('trial').onclick=()=>begin('race');$('start-trial').onclick=()=>begin('race');$('pause').onclick=()=>pauseGame();$('settings').onclick=()=>pauseGame(true);$('close-menu').onclick=closeMenu;$('resume').onclick=closeMenu;$('restart-race').onclick=()=>{closeMenu();begin('race');};$('back-title').onclick=()=>{closeMenu();state='intro';gate.visible=false;document.body.classList.remove('playing','racing');$('hud').classList.add('hidden');for(const id of ['intro','intro-location','intro-footer'])$(id).classList.remove('hidden');player.group.position.set(spawn.x,.08,spawn.z);player.group.rotation.y=0;speed=vx=vz=heading=0;};$('menu').addEventListener('cancel',e=>{e.preventDefault();closeMenu();});$('result').addEventListener('cancel',e=>e.preventDefault());$('race-again').onclick=()=>{$('result').close();begin('race');};$('free-roam').onclick=()=>{$('result').close();begin('free');};$('quality').onchange=e=>setQuality(e.target.value);$('camera-select').onchange=e=>cameraSwitch(Number(e.target.value));$('sound').onclick=()=>{enableSound();sound.enabled=!sound.enabled;$('sound').setAttribute('aria-label',sound.enabled?'Mute engine sound':'Enable engine sound');$('sound').querySelector('span').style.display=sound.enabled?'none':'block';toast(sound.enabled?'ENGINE SOUND ON':'ENGINE SOUND OFF');};
function toggleMap(){if(state!=='play')return;expandedMap=!expandedMap;document.querySelector('.map-panel').classList.toggle('expanded',expandedMap);$('map-button').setAttribute('aria-label',expandedMap?'Close expanded map':'Expand map');minimap.width=expandedMap?1000:480;minimap.height=expandedMap?1200:360;drawMap();}
$('map-button').onclick=toggleMap;
for(const btn of document.querySelectorAll('.swatch'))btn.onclick=()=>{carBodyMat.color.set(btn.dataset.color);document.querySelectorAll('.swatch').forEach(b=>{b.classList.toggle('active',b===btn);b.setAttribute('aria-pressed',String(b===btn));});};
const blocked=new Set(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','Tab']);
window.addEventListener('keydown',e=>{if(e.target.tagName==='SELECT')return;if(blocked.has(e.code)&&e.code!=='Tab')e.preventDefault();if(e.repeat)return;if(e.code==='Escape'){e.preventDefault();if($('menu').open)closeMenu();else if(state==='play')pauseGame();return;}if(e.code==='Enter'&&state==='intro'&&!paused){begin('free');return;}if(state!=='play'||paused)return;if(e.code==='KeyP'){pauseGame();return;}if(e.code==='KeyR'){resetCar();toast(mode==='race'?'RUN RESTARTED':'BACK ON THE ROAD');return;}if(e.code==='KeyC'){cameraSwitch();return;}if(e.code==='KeyM'){toggleMap();return;}keys.add(e.code);});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();if(state==='play'&&!paused)pauseGame();});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();if(state==='play'&&!paused)pauseGame();}});
for(const btn of document.querySelectorAll('[data-key]')){const clear=()=>{keys.delete(btn.dataset.key);btn.classList.remove('pressed');};btn.addEventListener('pointerdown',e=>{e.preventDefault();if(paused)return;btn.setPointerCapture(e.pointerId);keys.add(btn.dataset.key);btn.classList.add('pressed');});btn.addEventListener('pointerup',clear);btn.addEventListener('pointercancel',clear);btn.addEventListener('lostpointercapture',clear);}
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);});
let runningDt=0,slowFrames=0;
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);time+=dt;frame++;if(!paused){oceanMat.uniforms.time.value=time;updateTraffic(dt);if(state==='play'){const steps=Math.ceil(dt/(1/90));for(let i=0;i<steps&&!paused;i++)move(dt/steps);getCamera();camera.position.lerp(camDesired,1-Math.exp(-5*dt));lookTarget.lerp(camTarget,1-Math.exp(-7*dt));camera.lookAt(lookTarget);const targetFov=(cameraMode===2?66:53)+Math.min(Math.abs(speed)/65,1)*9+(boosting?5:0);camera.fov=THREE.MathUtils.damp(camera.fov,targetFov,3,dt);camera.updateProjectionMatrix();}else{const p=player.group.position;const drift=Math.sin(time*.07)*1.3;camera.position.set(p.x+11+drift,5.2,p.z+12.5);lookTarget.set(p.x+2,2,p.z-5);camera.lookAt(lookTarget);camera.fov=53;camera.updateProjectionMatrix();blob.position.set(p.x,.028,p.z);blob.rotation.z=0;}}
 const p=player.group.position;sun.position.set(p.x-130,170,p.z-230);sun.target.position.set(p.x,0,p.z-15);sky.position.copy(camera.position);gateArrow.position.y=10+Math.sin(time*2)*.55;gateArrow.rotation.y=time*.4;gateMat.opacity=.68+Math.sin(time*2)*.1;
 if(frame%3===0&&state==='play')updateHud();if(sound.ctx){const rpm=45+Math.abs(speed)*3.5+(boosting?40:0);sound.osc.frequency.setTargetAtTime(rpm,sound.ctx.currentTime,.08);sound.filter.frequency.setTargetAtTime(170+Math.abs(speed)*9,sound.ctx.currentTime,.1);sound.gain.gain.setTargetAtTime(sound.enabled&&!paused&&state==='play'?.028+Math.abs(speed)*.00045:0,sound.ctx.currentTime,.1);}
 composer.render();if(!started){started=true;$('loading').classList.add('hidden');}
}
try{const saved=localStorage.getItem('pacific-quality');if(['high','medium','low'].includes(saved))quality=saved;}catch{}setQuality(quality);updateTraffic(0);animate();
window.__pacific={getState:()=>({state,mode,paused,speed,heading,nitro,position:{x:player.group.position.x,z:player.group.position.z},checkpoint,raceTime,quality,distanceTravelled}),reset:resetCar};
